"""
Example of the application configuration file.
DO NOT EDIT THIS FILE.
Copy (and rename) this file into ./config.py first.
"""
# TODO comments

'''
Server config
'''
SERVER_PORT = 80
MONGO_PORT = ''
SERVER_ADDRESS = ''             # NB! Use the full url with the protocol prefix https://...
MONGO_ADDRESS = 'localhost'
SSL_VERIFY = True               # Whether to verify ssl certificates
REQUEST_TIMEOUT = 10            # Timeout for requests to gitlab & slack

'''
Google Sheets
'''
GOOGLE_SHEETS_URL = ''
GOOGLE_SHEETS_SHEET_NAME = ''
GOOGLE_SHEETS_COL_SLACK_UNAMES = ''  # name of the column with slack 'real names', i.e. 'Andree Prees'
GOOGLE_SHEETS_COL_GITLAB_UNAMES = '' # name of the column with gitlab usernames
GOOGLE_SHEETS_COL_GITLAB_REPOS = ''  # name of the column with gitlab repositories
GOOGLE_SHEETS_COLUMN_OFFSET = 1
GOOGLE_SHEETS_CLIENT_SECRET_PATH = ''

'''
Gitlab
'''
GITLAB_AUTH_TOKEN = ''
GITLAB_ROOT_URL = ''

'''
Slack
'''
SLACK_AUTH_TOKEN = ''

'''
Strings
'''
ISSUE_MESSAGE_TO_USER = 'You\'ve got an issue, sir!   :bug:'
ISSUE_MESSAGE_TO_AUTHOR = 'You\'ve opened an issue, sir!   :face_with_rolling_eyes:'
